apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  id: YXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBNlBCT0lNQkdZWk1GQ0o0NQphd3Nfc2VjcmV0X2FjY2Vz
  key: c19rZXkgPSBoTXNzcHRtUlpmYnNGR05HMjVEazBYR01mVXk5VWdWMGUxdW1RaVNWCg==

