apiVersion: apps/v1
kind: Deployment
metadata: 
  name: udagram-frontend
  labels: 
  app: udagram-frontend
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels: 
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-api-feed
        image: gabrielrockson/udagram-frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
            name: aws-credentials
        env:
        - name: URL
          valueFrom: 
            configMapKeyRef:
              name: env-configmap
              key: URL
        - name: AWS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_BUCKET_NAME
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom: 
            configMapKeyRef:
              name: env-configmap
              key: AWS_PROFILE
        - name: POSTGRES_HOST
          valueFrom: 
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom: 
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_DB
        - name: POSTGRES_USERNAME
          valueFrom: 
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: JWT_SECRET
      restartPolicy: Always
